//! # changepacks-dart
//!
//! Dart project support for changepacks.
//!
//! Implements project discovery and version management for pubspec.yaml files. Parses YAML
//! using the `yaml_serde` crate while maintaining formatting. Supports both single packages
//! and workspace configurations with pub as the package manager.

pub mod finder;
pub mod package;
pub mod workspace;

pub use finder::DartProjectFinder;

/// Default publish command for Dart projects. Shared by `DartPackage`
/// and `DartWorkspace` so a single edit here updates both trait impls.
pub(crate) const PUBLISH_COMMAND: &str = "dart pub publish";

/// Default dry-run publish command for Dart projects.
/// `dart pub publish --dry-run` performs the full pre-flight publish
/// validation (analysis, deps check, LICENSE/CHANGELOG detection) without
/// uploading. Users can override via `publishDryRun` in config.
pub(crate) const DRY_RUN_PUBLISH_COMMAND: &str = "dart pub publish --dry-run";

use std::path::Path;

use anyhow::{Context, Result};
use changepacks_core::UpdateType;
use changepacks_utils::{finalize_content, next_version_or_default};
use tokio::fs::{read_to_string, write};

/// Shared body for `DartPackage::update_version` and
/// `DartWorkspace::update_version`.
///
/// Consolidates the "read current version, compute next, write pubspec,
/// stash new version on `self`" 7-line sequence — previously duplicated
/// byte-for-byte between `DartPackage` and `DartWorkspace` — into ONE
/// source of truth. Both trait impls now delegate here so a future
/// rewording of the "reserve `0.0.0` when unversioned" fallback or the
/// `existing_version` derivation lands in exactly one place.
///
/// A shared helper (rather than a `macro_rules!` mirroring
/// `impl_node_publish_wiring!()`) is required because `#[async_trait]`
/// expansion runs BEFORE declarative-macro expansion — an `async fn`
/// generated by a macro invocation inside an `#[async_trait]` impl block
/// keeps its `async fn` desugaring instead of `async_trait`'s
/// `Pin<Box<dyn Future ...>>` transform, tripping E0195 against the
/// trait's transformed signature. Non-async macros (like
/// `impl_basic_accessors!()`) are unaffected. Rust-side deduplication is
/// unchanged: 14 lines of body → 6 lines of helper + 1 delegating line
/// per impl.
///
/// # Errors
/// Returns error if the version update or pubspec write fails.
pub(crate) async fn update_version_from_fields(
    version: &mut Option<String>,
    path: &Path,
    update_type: UpdateType,
) -> Result<()> {
    // Two-line "reserve `0.0.0` when unversioned" prelude consolidated
    // into `changepacks_utils::next_version_or_default` so the fallback
    // policy lives in ONE place across every language crate. See that
    // helper's doc for the Java/Rust carve-outs.
    let new_version = next_version_or_default(version.as_deref(), update_type)?;

    let existing_version = version.is_some();
    write_pubspec_version(path, &new_version, existing_version).await?;
    *version = Some(new_version);
    Ok(())
}

/// Update `pubspec.yaml` at `path` to set its `version` field to `new_version`,
/// preserving the file's YAML formatting (via `yamlpatch`/`yamlpath`) and its
/// trailing-newline shape (via `trailing_newline`).
///
/// Shared by `DartPackage::update_version` and `DartWorkspace::update_version`
/// so both paths emit byte-identical output. When `existing_version` is
/// `true`, replaces the existing `version` field; when `false`, adds a new
/// `version` field at the document root (needed for workspace roots that
/// declare no `version`).
///
/// # Errors
/// Returns error if the file cannot be read, is not valid YAML, or the write
/// fails.
pub(crate) async fn write_pubspec_version(
    path: &Path,
    new_version: &str,
    existing_version: bool,
) -> Result<()> {
    let pubspec_yaml_raw = read_to_string(path).await?;
    let patch = if existing_version {
        yamlpatch::Patch {
            operation: yamlpatch::Op::Replace(yaml_serde::Value::String(new_version.to_string())),
            route: yamlpath::route!("version"),
        }
    } else {
        yamlpatch::Patch {
            operation: yamlpatch::Op::Add {
                key: "version".to_string(),
                value: yaml_serde::Value::String(new_version.to_string()),
            },
            route: yamlpath::route!(),
        }
    };
    let patched = yamlpatch::apply_yaml_patches(
        &yamlpath::Document::new(&pubspec_yaml_raw).context("Failed to parse YAML")?,
        &[patch],
    )?;
    write(path, finalize_content(patched.source(), &pubspec_yaml_raw)).await?;
    Ok(())
}
