[package]
name = "changepacks-python"
version = "0.2.21"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Python project support for changepacks (pip, uv)"
readme = "../../README.md"

[dependencies]
changepacks-core.workspace = true
changepacks-utils.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["fs"] }
async-trait.workspace = true
toml_edit.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util", "macros"] }
rstest.workspace = true
changepacks-utils = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
