[package]
name = "changepacks-dart"
version = "0.2.21"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Dart project support for changepacks (pub)"
readme = "../../README.md"

[dependencies]
changepacks-core.workspace = true
changepacks-utils.workspace = true
async-trait.workspace = true
yaml_serde = "0.10"
anyhow.workspace = true
tokio = { workspace = true, features = ["fs"] }
yamlpatch = "1.28"
yamlpath = "1.28"

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true, features = ["test-util", "macros"] }
rstest.workspace = true
changepacks-utils = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
